fix

diff --git a/.github/workflows/test_python_examples.yaml b/.github/workflows/test_python_examples.yaml
--- a/.github/workflows/test_python_examples.yaml
+++ b/.github/workflows/test_python_examples.yaml
@@ -67,6 +67,12 @@ jobs:
             echo "--------------------"
             echo "*** $FILE ***"
             python3 $FILE > /dev/null
+            if [ $? -eq 0 ]; then
+              echo "OK"
+            else
+              echo "ERROR"
+              exit 1
+            fi
           done
 
       - name: Add qgis to Conda
